#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Go-live for #15 (docs/whatsapp-templates.md → Produksi). Run from Git Bash:
#   bash scripts/go-live.sh
# Values are remembered in the gitignored supabase/.env.production.local.

cd "$(dirname "$0")/.."
ENV_FILE="supabase/.env.production.local"
TOTAL_STAGES=14

# Enter runs the stage; n skips it (done on an earlier run).
run() {
  local r=""
  printf '  %s? Run this stage? [Y/n]%s ' "$YELLOW" "$RESET"
  read -r r || true
  [[ ! "$r" =~ ^[Nn] ]]
}

# Every stage after the first needs the project ref; recall it on re-runs.
PROJECT_REF=$(_existing PROJECT_REF || true)
dash() { printf 'https://supabase.com/dashboard/project/%s/%s' "$PROJECT_REF" "$1"; }
fn_url() { printf 'https://%s.supabase.co/functions/v1/%s' "$PROJECT_REF" "$1"; }

# submit NAME CATEGORY COMPONENTS_JSON asks Meta to review one template.
submit() {
  local name="$1" category="$2" components="$3" res
  res=$(curl -sS -X POST "https://graph.facebook.com/v23.0/$WABA_ID/message_templates" \
    -H "Authorization: Bearer $WHATSAPP_TOKEN" -H "Content-Type: application/json" \
    -d "{\"name\":\"$name\",\"language\":\"id\",\"category\":\"$category\",\"components\":$components}" || true)
  if [[ "$res" == *'"id"'* ]]; then
    printf '  %s✓ submitted%s %s\n' "$GREEN" "$RESET" "$name"
  else
    warn "$name: $res"
    SKIPPED+=("template $name (Meta said: $res)")
  fi
}
body() { printf '{"type":"BODY","text":"%s","example":{"body_text":[%s]}}' "$1" "$2"; }
YA_TIDAK='{"type":"BUTTONS","buttons":[{"type":"QUICK_REPLY","text":"YA"},{"type":"QUICK_REPLY","text":"TIDAK"}]}'

banner "Kinfolk go-live (#15)"

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase: link the hosted project"
if run; then
  open_url "https://supabase.com/dashboard/projects"
  step "Open the production project. The ref is the id in the URL: /project/<ref>."
  ask PROJECT_REF "Project ref:"
  write_env PROJECT_REF "$PROJECT_REF"
  note "The CLI may open a browser to log in, then ask for the database password."
  npx supabase login
  npx supabase link --project-ref "$PROJECT_REF"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase: push migrations"
say "Applies every migration in supabase/migrations to the hosted database."
if run && confirm "Push migrations to $PROJECT_REF now?"; then
  npx supabase db push
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Meta: WhatsApp Business credentials"
if run; then
  open_url "https://developers.facebook.com/apps"
  step "Open the Kinfolk app → WhatsApp → API Setup."
  step "Copy the production sender's 'Phone number ID' and the 'WhatsApp Business Account ID'."
  ask WHATSAPP_PHONE_NUMBER_ID "Phone number ID:"
  ask WABA_ID "WhatsApp Business Account ID:"
  write_env WHATSAPP_PHONE_NUMBER_ID "$WHATSAPP_PHONE_NUMBER_ID"
  write_env WABA_ID "$WABA_ID"
  step "App settings → Basic → App secret → Show → copy."
  ask_secret WHATSAPP_APP_SECRET "App secret:"
  write_env WHATSAPP_APP_SECRET "$WHATSAPP_APP_SECRET"
  open_url "https://business.facebook.com/settings/system-users"
  say "The API Setup token expires in 24 h, so use a permanent system-user token:"
  step "System users → pick or add an admin system user → Assign assets: the Kinfolk app and the WhatsApp account."
  step "Generate token → Kinfolk app → expiry Never → whatsapp_business_messaging + whatsapp_business_management → copy."
  ask_secret WHATSAPP_TOKEN "System user token:"
  write_env WHATSAPP_TOKEN "$WHATSAPP_TOKEN"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Meta: submit the 12 message templates"
say "Copy is owner-approved (#3, #4, #13, #23, #24) and matches template_body(). Don't edit it here."
note "A rejection is kept for the summary; bring it back before changing any copy."
if run; then
  WABA_ID=$(_existing WABA_ID || true); WHATSAPP_TOKEN=$(_existing WHATSAPP_TOKEN || true)
  submit kinfolk_otp AUTHENTICATION '[{"type":"BODY","add_security_recommendation":true},{"type":"FOOTER","code_expiration_minutes":10},{"type":"BUTTONS","buttons":[{"type":"OTP","otp_type":"COPY_CODE"}]}]'
  submit kinfolk_invite UTILITY "[$(body '{{1}} mengundang Anda ke lingkaran perawatan {{2}} di Kinfolk. Buka tautan ini untuk bergabung, tanpa perlu pasang app: {{3}}' '["Sri","Tukiman","https://kinfolk.id/undangan?t=contoh"]')]"
  submit kinfolk_swap_ask UTILITY "[$(body '{{1}} bertanya: bisa ambil {{2}} {{3}}? Balas YA atau TIDAK.' '["Sri","telepon cek malam Tukiman","Minggu 4 Okt, 19.00"]'),$YA_TIDAK]"
  submit kinfolk_swap_yes UTILITY "[$(body '{{1}} pegang {{2}} hari {{3}}.' '["Budi","telepon cek malam","Minggu 4 Okt"]')]"
  submit kinfolk_swap_no UTILITY "[$(body '{{1}} tidak bisa ambil {{2}} hari {{3}}.' '["Budi","telepon cek malam","Minggu 4 Okt"]')]"
  submit kinfolk_drive_ask UTILITY "[$(body '{{1}} bertanya: bisa mengantar {{2}} ke {{3}}, {{4}}? Balas YA atau TIDAK.' '["Sri","Tukiman","Kontrol neurologi","Kam, 1 Okt · 09.00, berangkat 08.15"]'),$YA_TIDAK]"
  submit kinfolk_drive_yes UTILITY "[$(body '{{1}} mengantar {{2}} {{3}}.' '["Budi","Tukiman","Kam, 1 Okt · 09.00"]')]"
  submit kinfolk_drive_no UTILITY "[$(body '{{1}} tidak bisa mengantar {{2}} {{3}}.' '["Budi","Tukiman","Kam, 1 Okt · 09.00"]')]"
  submit kinfolk_drive_reminder UTILITY "[$(body 'Hari ini: antar {{1}} ke {{2}} jam {{3}}.' '["Tukiman","Kontrol neurologi","09.00, berangkat 08.15. Bawa: KTP, kartu BPJS"]')]"
  submit kinfolk_duty_reminder UTILITY "[$(body 'Hari ini: {{1}} jam {{2}}.' '["telepon cek malam","19.00"]')]"
  submit kinfolk_visit_note UTILITY "[$(body '{{1}} menulis catatan kunjungan {{2}}. {{3}}.' '["Sri","Tukiman","Kontrol neurologi: fisioterapi 2x/minggu, MRI ulang 3 bulan lagi"]')]"
  submit kinfolk_bp_high UTILITY "[$(body 'Tensi {{1}} malam ini {{2}}, 140 ke atas. Dicatat oleh {{3}}.' '["Tukiman","152/90","Sri"]')]"
  pause "Press Enter when you've read the results"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Twilio: SMS fallback"
if run; then
  open_url "https://console.twilio.com"
  step "Account Info on the console home: copy Account SID and Auth Token."
  ask TWILIO_ACCOUNT_SID "Account SID (AC…):"
  ask_secret TWILIO_AUTH_TOKEN "Auth Token:"
  step "Phone Numbers → Active numbers: copy a sender that can text Indonesia, in E.164 (+…)."
  ask TWILIO_FROM "Sender number:"
  write_env TWILIO_ACCOUNT_SID "$TWILIO_ACCOUNT_SID"
  write_env TWILIO_AUTH_TOKEN "$TWILIO_AUTH_TOKEN"
  write_env TWILIO_FROM "$TWILIO_FROM"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Custom domain for the web pages"
say "*.supabase.co serves function HTML as text/plain, so both pages need your own domain."
say "On your domain host (e.g. a Cloudflare Worker or a reverse proxy), forward:"
step "an invitation path (e.g. https://kinfolk.id/undangan) → $(fn_url invitation), query string kept"
step "an emergency path (e.g. https://kinfolk.id/darurat) → $(fn_url emergency), query string kept"
note "The functions are deployed in the next stage."
if run; then
  ask INVITATION_URL "Public invitation URL:"
  ask EMERGENCY_URL "Public emergency URL:"
  write_env INVITATION_URL "$INVITATION_URL"
  write_env EMERGENCY_URL "$EMERGENCY_URL"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase: deploy Edge Functions"
say "send-otp, invite, invitation, whatsapp, emergency, all with --no-verify-jwt."
if run && confirm "Deploy all five to $PROJECT_REF?"; then
  for f in send-otp invite invitation whatsapp emergency; do
    npx supabase functions deploy "$f" --no-verify-jwt --project-ref "$PROJECT_REF"
  done
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase Auth: Send SMS hook and phone sign-in"
if run; then
  open_url "$(dash auth/hooks)"
  step "Add hook → Send SMS → type HTTPS → URL $(fn_url send-otp)"
  step "Generate secret → copy it (starts v1,whsec_) → Create."
  ask_secret SEND_SMS_HOOK_SECRET "Hook secret:"
  write_env SEND_SMS_HOOK_SECRET "$SEND_SMS_HOOK_SECRET"
  open_url "$(dash auth/providers)"
  step "Phone → enable → SMS OTP expiry 600 seconds → Save."
  note "SMS provider fields can stay empty; the hook sends instead."
  pause "Press Enter when phone sign-in is saved"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase: function secrets"
if run; then
  for k in WHATSAPP_VERIFY_TOKEN NOTIFY_SECRET; do
    [[ -n "$(_existing "$k" || true)" ]] || write_env "$k" "$(openssl rand -hex 32)"
  done
  tmp=$(mktemp)
  for k in SEND_SMS_HOOK_SECRET WHATSAPP_PHONE_NUMBER_ID WHATSAPP_TOKEN WHATSAPP_APP_SECRET WHATSAPP_VERIFY_TOKEN \
           NOTIFY_SECRET TWILIO_ACCOUNT_SID TWILIO_AUTH_TOKEN TWILIO_FROM INVITATION_URL; do
    v=$(_existing "$k" || true)
    if [[ -n "$v" ]]; then printf '%s=%s\n' "$k" "$v" >> "$tmp"; else warn "$k is empty; run its stage first"; fi
  done
  if confirm "Set $(wc -l < "$tmp" | tr -d ' ') secret(s) on $PROJECT_REF?"; then
    npx supabase secrets set --env-file "$tmp" --project-ref "$PROJECT_REF"
  fi
  rm -f "$tmp"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Meta: webhook for replies"
if run; then
  open_url "https://developers.facebook.com/apps"
  step "Kinfolk app → WhatsApp → Configuration → Webhook → Edit."
  step "Callback URL: $(fn_url whatsapp)"
  step "Verify token: $(_existing WHATSAPP_VERIFY_TOKEN || echo '<run the secrets stage first>')"
  step "Verify and save, then Webhook fields → subscribe to 'messages'."
  pause "Press Enter when Meta shows the webhook verified"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase: minute job for notifications"
if run; then
  open_url "$(dash sql/new)"
  step "Paste and run this once:"
  printf '\n%s\n\n' "create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;
select cron.schedule('whatsapp', '* * * * *', \$\$ select net.http_post('$(fn_url whatsapp)', '{}'::jsonb, headers := '{\"authorization\": \"Bearer $(_existing NOTIFY_SECRET || true)\", \"content-type\": \"application/json\"}'::jsonb) \$\$);"
  pause "Press Enter when it returned a job id"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "App: point it at the hosted project"
if run; then
  open_url "$(dash settings/api-keys)"
  step "Copy the publishable key (starts sb_publishable_)."
  ask PUBLISHABLE_KEY "Publishable key:"
  write_env PUBLISHABLE_KEY "$PUBLISHABLE_KEY"
  EMERGENCY_URL=$(_existing EMERGENCY_URL || true)
  ENV_FILE=local.properties write_env kinfolk.supabaseUrl "https://$PROJECT_REF.supabase.co"
  ENV_FILE=local.properties write_env kinfolk.publishableKey "$PUBLISHABLE_KEY"
  ENV_FILE=local.properties write_env kinfolk.emergencyUrl "$EMERGENCY_URL"
  if confirm "Build the Android debug app now?"; then ./gradlew :androidApp:assembleDebug; fi
  note "iOS: rebuild from Xcode."
  pause
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Wait for Meta template approval"
open_url "https://business.facebook.com/wa/manage/message-templates/"
say "All 12 kinfolk_* templates must show Active before the real-number tests."
pause "Press Enter when they're approved"

# ──────────────────────────────────────────────────────────────────────────
stage "Real-number tests"
say "Install the new build on a real phone. y = worked; anything else lands in the summary."
check() { confirm "$1" || SKIPPED+=("failed: $1"); }
check "Sign-in OTP arrives on WhatsApp"
check "'Kirim lewat SMS' sends the OTP by SMS"
check "A number not on WhatsApp gets the OTP by SMS"
check "An Invitation arrives on WhatsApp and the web page accepts it on a phone"
check "An Invitation to a number not on WhatsApp arrives by SMS"
check "A swap request arrives on WhatsApp and a YA reply updates the app"
check "The Emergency Info QR opens the page on a phone"
note "Function logs: $(dash functions)"

finish
